version: '2'
services:
  microservice-random-question:
    container_name: microservice-random-question
    build: ./microservices/randomQuestion
    image: quizrt/microservice-random-question:0.1.0
    network_mode: host
    restart: always
    depends_on:
      - db
    environment:
      MONGO_HOST: localhost
      MONGO_PORT: 27017
      MONGO_DB_NAME: quizRT
  db:
    container_name: db
    image: mvertes/alpine-mongo
    restart: always
    volumes:
      - ~/quizrt_mongodb_vol:/data/db
    expose:
      - 27017
    ports:
      - 27017:27017
  redis:
    container_name: redis
    image: smebberson/alpine-redis
    restart: always
    expose:
      - 6379
    ports:
      - 6379:6379
